name: "Tox Tests"

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Tox test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tox tests
        id: test
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env:
          - py36-django22
          - py36-django32
          - py37-django22
          - py37-django32
          - py38-django22
          - py38-django32
          - py38-django40
          - py39-django22
          - py39-django32
          - py39-django40
          - py310-django32
          - py310-django40
